### ISSUE TITLE
Can't cache to artifact registry

### ISSUE THREAD

**Issue by dmzrio** [persona-id/gcp-artifact-registry-docker-proxy#27]
I try use this apps, but failed to store cache.
what i'm missing?

My env setup.
```
      - name: DOCKER_INSECURE_REGISTRY
        value: "127.0.0.1:1234"
        
      - name: DOCKER_REGISTRY_MIRROR
        value: "http://127.0.0.1:1234"
      
      - name: PROXY_LISTEN
        value: "127.0.0.1:1234"
      
      - name: PROXY_REGISTRY
        value: "https://asia-southeast1-docker.pkg.dev/example/public"
```

github action

```
steps:
   - name: Authenticate to Google Cloud with SA
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}
        
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: ${{ inputs.gcloud_components }}

    - name: Register gcloud as a docker credential helper
      shell: bash
      run: |-
        gcloud auth configure-docker ${{ inputs.artifact_registry_host }} --project ${{ inputs.project_id }} --quiet

      - name: gcp-artifact-registry-docker-proxy
        run: |
          wget https://github.com/persona-id/gcp-artifact-registry-docker-proxy/releases/download/v1.4.0/gcp-artifact-registry-docker-proxy_Linux_x86_64.tar.gz
          tar -zxvf gcp-artifact-registry-docker-proxy_Linux_x86_64.tar.gz
          ./gcp-artifact-registry-docker-proxy &

      - run: docker pull nginx:latest
```

i try run this workflow, but nginx:latest doesn't cache to my artifact registry.
